Filtro more_km_restantes implementado y testeado a mano
UB-ES-2020/Mooving pull request #131
Opened 2020-11-20 21:43 UTC by miguelMarchPiris

Ya funciona el filtro en el backend y lo he testeado usando postman en sus 4 posibles combinaciones.

Antes de hacerme el review necesito estar seguro de que a @lwangwan le parece bien lo que he puesto como cosas en el JSON. Esto está en la issue 14.1 JSON. Lo he explicado ahí todo. @lwangwan pon un comentario aquí o por donde sea cuando hayas decidido si te parece bien lo del json.

2020-11-24 10:40 UTC, lwangwan reviewed
En el constantes.py sale: 
'AVAILABLE', # Disponibles para el usuario
 'ACTIVE', # La gente la esta utilizando

Todas las combinaciones de get estan correctos.

2020-11-24 10:40 UTC, lwangwan commented on flaskProject/resources/motos.py
> +        list_and.append(MotoModel.state == "ACTIVE")
Creo que al final dijimos usar AVAILABLE.

2020-11-24 10:41 UTC, lwangwan approved these changes

2020-11-26 19:23 UTC, SrLimoncio requested changes
Hay que cambiar el estado ACTIVE por AVALIABLE en los metodos de mostrar motos al cliente

2020-11-27 18:34 UTC, merged